"use client";

import Footer from "@/components/Footer"
import {Inter} from "next/font/google"
import "./globals.css"
import Navigation from '@/components/Navigation'
import {useEffect} from "react";
import {supabase} from "@/lib/supabase";

const inter = Inter({ subsets: ["latin"] })

// export const metadata: Metadata = {
//   title: {
//     template: "%s | Calendar Booking App",
//     default: "Calendar Booking App",
//   },
//   description: "Generated by Calendar Booking App",
// }

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {

  useEffect(() => {
    const { data: listener } = supabase.auth.onAuthStateChange((event, session) => {
      console.log('Auth state changed:', event);
      if (event === 'SIGNED_IN') {
        console.log('로그인 완료:', session?.user);
      }
    });

    return () => {
      listener.subscription.unsubscribe();
    };
  }, []);

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="min-h-screen flex flex-col">
          <Navigation />
          <main className="flex-grow">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  )
}
