import Footer from "@/components/Footer"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import Header from '@/components/Header'

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: {
    template: "%s | Calendar Booking App",
    default: "Calendar Booking App",
  },
  description: "Generated by Calendar Booking App",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <div className="min-h-screen flex flex-col">
          <Header />
          <main className="flex-grow">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  )
}
